
-- Example use:
 
CALL MONITORING.AGENT.QUERY_MONITORING();

-- OR

EXECUTE TASK MONITORING.AGENT.WEEKLY_MONITORING_TASK;

SELECT MAX(run_timestamp) FROM MONITORING.AGENT.QUERY_INSIGHTS_HISTORY;

SELECT * FROM MONITORING.AGENT.AGENT_FINDINGS ORDER BY run_timestamp desc;
SELECT * FROM MONITORING.AGENT.QUERY_INSIGHTS_HISTORY ORDER BY run_timestamp desc;
SELECT * FROM MONITORING.AGENT.QUERY_HISTORY_HISTORY ORDER BY run_timestamp desc;
SELECT * FROM MONITORING.AGENT.COST_SPIKES ORDER BY run_timestamp desc
 
EXECUTE IMMEDIATE
$$
DECLARE
    last_run TIMESTAMP_NTZ;
BEGIN

    CALL MONITORING.AGENT.RUN_MONITORING_QUERIES(7);

    SELECT MAX(run_timestamp) INTO :last_run FROM MONITORING.AGENT.QUERY_INSIGHTS_HISTORY;

    CALL MONITORING.AGENT.SEND_FINDINGS_TO_CORTEX(:last_run, 'claude-3-7-sonnet');

    CALL MONITORING.AGENT.SEND_FINDINGS_EMAIL(:last_run);

END;
$$;